# Generated by Django 3.1.6 on 2021-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='desc',
            field=models.TextField(max_length=600),
        ),
    ]
